CREATE DATABASE IF NOT EXISTS QLNVBCHLapTop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE QLNVBCHLapTop;

-- Bảng Nhà Cung Cấp
CREATE TABLE IF NOT EXISTS NhaCungCap (
    MaNCC INT AUTO_INCREMENT PRIMARY KEY,
    TenNCC VARCHAR(255) NOT NULL,
    DiaChi VARCHAR(255),
    SDT VARCHAR(20)
);

-- Bảng Khách Hàng
CREATE TABLE IF NOT EXISTS KhachHang (
    MaKH INT AUTO_INCREMENT PRIMARY KEY,
    TenKH VARCHAR(255) NOT NULL,
    GioiTinh VARCHAR(10),
    DiaChi VARCHAR(255),
    SDT VARCHAR(20) UNIQUE,
    Email VARCHAR(100) UNIQUE
);

-- Bảng Sản Phẩm (đầy đủ cấu hình laptop)
CREATE TABLE IF NOT EXISTS SanPham (
    MaSP INT AUTO_INCREMENT PRIMARY KEY,
    LoaiMay VARCHAR(100),
    TenSP VARCHAR(255) NOT NULL,
    CPU VARCHAR(100),
    GPU VARCHAR(100),
    RAM INT,
    OCung VARCHAR(100),
    KichThuocMH FLOAT,
    DoPhanGiaiMH VARCHAR(50),
    CanNang FLOAT,
    SLTrongKho INT NOT NULL,
    GiaBan DOUBLE NOT NULL,
    GiaNhap DOUBLE,
    ThoiGianBaoHanh INT,
    MaNCC INT,
    FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC) ON DELETE SET NULL
);

-- Bảng Hóa Đơn Bán Hàng
CREATE TABLE IF NOT EXISTS HoaDonBanHang (
    MaHDBH INT AUTO_INCREMENT PRIMARY KEY,
    NgayTao DATE NOT NULL,
    LoaiHD VARCHAR(50) NOT NULL,
    TongTien DOUBLE NOT NULL,
    TienCoc DOUBLE,
    LaiSuat DOUBLE DEFAULT 0,
    ThoiHanTG INT DEFAULT 0,
    TienGopHangThang DOUBLE DEFAULT 0,
    SoTienConLai DOUBLE DEFAULT 0,
    TrangThai VARCHAR(50)
);

-- Bảng Chi Tiết Hóa Đơn Bán Hàng
CREATE TABLE IF NOT EXISTS ChiTietHDBH (
    MaHDBH INT,
    MaSP INT,
    SoLuong INT NOT NULL,
    TongTien DOUBLE NOT NULL,
    PRIMARY KEY (MaHDBH, MaSP),
    FOREIGN KEY (MaHDBH) REFERENCES HoaDonBanHang(MaHDBH) ON DELETE CASCADE,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);

-- Bảng Thanh Toán
CREATE TABLE IF NOT EXISTS ThanhToan (
    MaTT INT AUTO_INCREMENT PRIMARY KEY,
    MaHDBH INT NOT NULL,
    MaKH INT NOT NULL,
    NgayTT DATE NOT NULL,
    TienThanhToan DOUBLE NOT NULL,
    HinhThucTT VARCHAR(50),
    FOREIGN KEY (MaHDBH) REFERENCES HoaDonBanHang(MaHDBH) ON DELETE CASCADE,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
);
